/*THIS DO-FILE OPENS THE DATA FILE CALLED
analysis.dta THAT IS GENERATED BY THE
DO-FILE CALLED processing.do,

THEN GENERATES ALL THE FIGURES AND NUMERICAL
OUTPUT NEEDED FOR THE DATA APPENDIX
*/

*WHEN YOU RUN THIS DO-FILE, MAKE SURE THAT
**********1) STATA'S WORKING DIRECTORY IS SET 
*************TO THE "Command-Files" FOLDER
**********2) THE analysis.dta DATA FILE IS 
*************SAVED IN THE "Analysis-Data" FOLDER

clear
set more off

*START BY OPENING THE analysis.dta
*DATA FILE
use ../Analysis-Data/analysis.dta

********************************************************
********************************************************
*FOR EACH OF THE 5 VARIABLES THAT WILL BE REPRESENTED IN 
*THE DATA APPENDIX, CREATE THE OUTPUT THAT WILL BE NEEDED
********************************************************
********************************************************

*FOR THE VARIABLE drunk

	*Generate a table showing the frequency distribution and 
	*the percent frequency distribution
	
		tabulate drunk
	
	/* NOTE: This command will tell us the number of observations with 
	non-missing values of drunk, but it will not show the number of 
	observations with missing values of drunk.  
	
	There are many ways we could get Stata to show us the number of 
	observations with missing values of drunk.  Here is one way to do it:
	*/
	
		tabulate drunk, missing
	
	/*In this case there are no missing values, so the output of the command 
	"tablate drunk, missing" is identical to the output from 
	"tabulate drunk".*/
	
	*Generate a bar chart illustrating the percent frequency distribution
	*Save bar chart in "Graphs" folder (using relative directory path)
	
		graph bar, over(drunk)  ///
			ytitle(Percent Frequency)  ///
			ti("Percent Frequency Distribution of drunk") ///
			legend(label(1 0) label(2 1)) ///
			saving(../Graphs/For-Data-Appendix/drunk-distn.gph, replace)
	
*FOR THE VARIABLE hsdrunk

	*Generate a table showing the frequency distribution and 
	*the percent frequency distribution
	
		tabulate hsdrunk
	
	*To see the number of observations with missing values
		tabulate hsdrunk, missing
	
	*Generate a bar chart illustrating the percent frequency distribution
	*Save bar chart in "Graphs" folder (using relative path)
	
		graph bar, over(hsdrunk) ///
			ytitle(Percent Frequency) ///
			legend(label(1 0) label(2 1)) ///
			ti("Percent Frequency Distribution of hsdrunk") ///
			saving(../Graphs/For-Data-Appendix/hsdrunk-drunk.gph, replace)
				
*FOR THE VARIABLE free

	*Generate a table showing the frequency distribution and 
	*the percent frequency distribution
	
		tabulate free
	
	*To see the number of observations with missing values
	
		tabulate free, missing
	
	*Generate a bar chart illustrating the percent frequency distribution
	*Save bar chart in "Graphs" folder (using relative path)
	
		graph bar, over(free)  ///
			ytitle(Percent Frequency) ///
			legend(label(1 0) label(2 1)) ///
			ti("Percent Frequency Distribution of free") ///
			saving(../Graphs/For-Data-Appendix/free-dist.gph, replace)
		
*FOR THE VARIABLE volfree

	*Generate a table showing the frequency distribution and 
	*the percent frequency distribution
	
		tabulate volfree
	
	*To see the number of observations with missing values
	
		tabulate volfree, missing
	
	/*In this case, 2428 cases have a missing value of volalcfree.  To be precise,
	the value of volalcfree for these cases should be called "out of universe,"
	because it is in fact impossible to give a value of volalcfree for any of 
	these cases:  The cases for which volalcfree has a missing value are those 
	in which the student does not live in alcohol-free housing; since volalcfree
	indicates why a student lives in alcohol-free housing (by request vs. 
	assigned), it is not possible to define volaclfree for students who do not
	live in alcohol-free housing).*/
	
	*Generate a bar chart illustrating the percent frequency distribution
	*Save bar chart in "Graphs" folder (using relative path)
	
		graph bar, over(volfree) ///
			ytitle(Percent Frequency) ///
			legend(label(1 0) label(2 1)) ///
			ti("Percent Frequency Distribution of volfree") ///
			saving(../Graphs/For-Data-Appendix/volfree-dist.gph, replace)
		
*FOR THE VARIABLE housing

	*Generate a table showing the frequency distribution and 
	*the percent frequency distribution
	
		tabulate housing
	
	*To see the number of observations with missing values
	
		tabulate housing, missing
	
	*Generate a bar chart illustrating the percent frequency distribution
	*Save bar chart in "Graphs" folder (using relative path)
		
		graph bar, over(housing, ///
			relabel(1  ///
				`""Not" "Alcohol-Free""'  ///
				2 "Assigned" ///
				3 `""All Housing" "Alcohol-Free""'  ///
				4 "Requested"  ///
				)) ///	
		ytitle(Percent Frequency) ///
		ti("Percent Frequency Distribution of housing") ///
		saving(../Graphs/For-Data-Appendix/housing-dist.gph, replace)
		
	
